### ISSUE TITLE
Invitation to "join forces" and merge your code into dendextend

### ISSUE THREAD

**Issue by talgalili** [NicolasH2/ggdendroplot#3]
Hey @NicolasH2 ,
Nice to e-meet :)

I'm the main author of [dendextend](https://github.com/talgalili/dendextend/), an R package for "Extending 'dendrogram' Functionality in R", and also a co-author of the [heatmaply](https://github.com/talgalili/heatmaply) package.
The dendextend package already offers an (IMHO) very nice integration with ggplot2 (see [here](https://talgalili.github.io/dendextend/articles/dendextend.html#ggplot2-integration-1)). There is also a ggheatmap implementation through the heatmaply package (see details [here](https://cran.r-project.org/web/packages/heatmaply/vignettes/heatmaply.html#ggheatmap)).

Currently, dendextend has been downloaded 3.5 million times, and is downloaded each month (currently), around ~102 thousand  times.

Looking at the code you wrote, it seems that you are re-doing some of the existing work, which is a bit of a shame (IMHO).

If you are interested instead to look at the existing dendextend code (for example, the part that deals with ggplot2, see [here](https://github.com/talgalili/dendextend/blob/master/R/ggdend.R)) - I'd be very happy to collaborate with you. Namely, you're invited to contribute pull requests to whatever related feature you have in mind, and I'd review/approve them - and you will be a co-author on the relevant package (dendextend | heatmaply).

What do you think?

(feel free to respond to me here, or via email: tal.galili@gmail.com)

**Comment by NicolasH2** [comment]
Hi @talgalili ,
Nice to meet you too, thanks for the post!

Your package is extremely advanced, than mine. My package was really just for me to have a quick solution without having to adjust too many parameters and I thought maybe some other people could also find it helpful.

I didn't know about your package before I wrote this and any overlap with your code is really coincidence. I just took R's hclust output as a starting point and worked my way through from there, with colors and heatmap following as an afterthought. I basically just wanted to have a dendrogram in ggplot at whatever position without much complicated code. 

Anyway, it is really nice of you to invite me to work on your package, I will have a look at it. But I have to be honest, I will probably not be able to improve much there...your package seems extremely complex and can already do much more than mine anyway. So I would love to contribute and I will see if there is something I can do, but if you don't hear anything from me in this regard, it is probably because I just have nothing to add ;)

**Comment by talgalili** [comment]
Thanks Nicolas for your kind words :)

There are always things to improve on (from better testing, to better
defaults, more arguments, bug fixes, better documentation, and new
features).
I encourage you to start using dendextend to your use-cases, find things
that are not "working" the way you want them - and suggest PR. I'd be happy
for your insights/code.

Cheers,
Tal
